import {
  wa1,
  wa1_1,
  wa1_2,
  wa1_3,
  wa1_4,
  wa1_5,
  wa2_1,
  wa2_2,
  wa2_3,
  wa3,
  wa3_1,
  wa3_2,
  wa5,
  wa5_4,
  wa5_5_1,
  wa5_5_2,
} from '@/json/index'

const strokeColor = '#5679ea'
// const strokeColor = '#33eaff'
const fillColor = '#5679ea'
// const fillColor = '#33eaff'
const strokeStyle = 'solid'

export const WA = {
  center: { lng: 107.46225547834213, lat: 27.181585242775864 },
  areas: [
    {
      name: '区块一',
      alias: '瓮安园区：区块一',
      path: wa1,
      strokeColor,
      fillColor,
      strokeStyle,
      polygon: null,
      showPrism: false,
      showTip: true,
    },
    {
      name: '区块一',
      alias: '瓮安园区：区块一',
      path: wa1_1,
      strokeColor,
      fillColor,
      strokeStyle,
      polygon: null,
      showPrism: true,
      showTip: false,
    },
    {
      name: '区块一',
      alias: '瓮安园区：区块一',
      path: wa1_2,
      strokeColor,
      fillColor,
      strokeStyle,
      polygon: null,
      showPrism: true,
      showTip: false,
    },
    {
      name: '区块一',
      alias: '瓮安园区：区块一',
      path: wa1_3,
      strokeColor,
      fillColor,
      strokeStyle,
      polygon: null,
      showPrism: true,
      showTip: false,
    },
    {
      name: '区块一',
      alias: '瓮安园区：区块一',
      path: wa1_4,
      strokeColor,
      fillColor,
      strokeStyle,
      polygon: null,
      showPrism: true,
      showTip: false,
    },
    {
      name: '区块一',
      alias: '瓮安园区：区块一',
      path: wa1_5,
      strokeColor,
      fillColor,
      strokeStyle,
      polygon: null,
      showPrism: true,
      showTip: false,
    },
    {
      name: '区块二',
      alias: '瓮安园区：区块二',
      path: wa2_1,
      strokeColor,
      fillColor,
      strokeStyle,
      polygon: null,
      showPrism: true,
      showTip: true,
    },
    {
      name: '区块二',
      alias: '瓮安园区：区块二',
      path: wa2_2,
      strokeColor,
      fillColor,
      strokeStyle,
      polygon: null,
      showPrism: true,
      showTip: false,
    },
    {
      name: '区块二',
      alias: '瓮安园区：区块二',
      path: wa2_3,
      strokeColor,
      fillColor,
      strokeStyle,
      polygon: null,
      showPrism: true,
      showTip: false,
    },
    {
      name: '区块三',
      alias: '瓮安园区：区块三',
      path: wa3,
      strokeColor,
      fillColor,
      strokeStyle,
      polygon: null,
      showPrism: false,
      showTip: true,
    },
    {
      name: '区块三',
      alias: '瓮安园区：区块三',
      path: wa3_1,
      strokeColor,
      fillColor,
      strokeStyle,
      polygon: null,
      showPrism: true,
      showTip: false,
    },
    {
      name: '区块三',
      alias: '瓮安园区：区块三',
      path: wa3_2,
      strokeColor,
      fillColor,
      strokeStyle,
      polygon: null,
      showPrism: true,
      showTip: false,
    },
    {
      name: '',
      alias: '',
      path: wa5,
      strokeColor,
      fillColor,
      strokeStyle,
      polygon: null,
      showPrism: false,
    },
    {
      name: '区块四',
      alias: '瓮安园区：区块四',
      path: wa5_4,
      strokeColor,
      fillColor,
      strokeStyle,
      polygon: null,
      showPrism: true,
      showTip: true,
    },
    {
      name: '区块五',
      alias: '瓮安园区：区块五',
      path: wa5_5_1,
      strokeColor,
      fillColor,
      strokeStyle,
      polygon: null,
      showPrism: true,
      showTip: true,
    },
    {
      name: '区块五',
      alias: '瓮安园区：区块五',
      path: wa5_5_2,
      strokeColor,
      fillColor,
      strokeStyle,
      polygon: null,
      showPrism: true,
      showTip: false,
    },
  ],
}
